is: [ auth ]
type:
  collection-optional:
    humanName: event source template
    schemaBaseName: eventSourceTemplate
    exampleGetResponse: !include ../../examples/templates/eventSources/response-array-get.json
    examplePostRequest: !include ../../examples/templates/eventSources/request-post.json
    examplePostError: !include ../../examples/templates/eventSources/response-post-error.json
get:
  description: Get all public event source templates.
  responses:
    200:
      description: List of event source templates or empty list `[]`. Only the `public` event source templates are returned.

/{eventSourceId}:
  is: [ auth ]
  type:
    member:
      humanName: event source template
      schemaBaseName: eventSourceTemplate
      identifierName: eventSourceTemplateId
      exampleGetResponse: !include ../../examples/templates/eventSources/response-get.json
      examplePatchRequest: !include ../../examples/templates/eventSources/request-patch.json
      examplePatchError: !include ../../examples/templates/eventSources/response-patch-error.json
  get:

  /eventTypes: !include eventTypes.raml
