/organizations:
  is: [ auth ]
  type:
    collection-optional:
      humanName: organization
      schemaBaseName: organization
      exampleGetResponse: !include ../../examples/organizations/response-array-get.json
      examplePostRequest: !include ../../examples/organizations/request-post.json
      examplePostError: !include ../../examples/organizations/response-post-error.json
  get:
    description: Retrieve the list of all organization where the user is part of.

  /templates:
    description: Management of the iFLUX templates for all user's organizations.

    /eventSources: !include eventSources.raml

  /{organizationId}/templates:
    description: Management of the iFLUX templates by organization.

    uriParameters:
      organizationId:
        description: The unique identifier of the organization.
        type: integer
        example: 1
        minimum: 1

    /eventSources: !include templates/eventSources.raml
