/signin:
  description: Allow the users to authenticate and retrieve the JSON Web Token
  post:
    body:
      schema: auth-signin-post-req
      example: !include ../examples/auth/request-signin-post.json
    responses:
      200:
        description: Authentication done correctly.
        body:
          schema: auth-signin-post-res
          example: !include ../examples/auth/response-signin-post.json
      401:
        description: Most probably bad credentials were provided.