/organizations:
  is: [ auth ]
  type:
    collection-optional:
      humanName: organization
      schemaBaseName: organization
      exampleGetResponse: !include ../examples/organizations/response-array-get.json
      examplePostRequest: !include ../examples/organizations/request-post.json
      examplePostError: !include ../examples/organizations/response-post-error.json
  get:
    description: Retrieve the list of all organization where the user is part of.
